language: go
go:
- 1.x
services:
- docker
addons:
  ssh_known_hosts: fsantiago.info
jobs:
  include:
  - stage: Build & Publish
    name: Build
    install: go get -u golang.org/x/lint/golint
    script: make build && scripts/publish.sh
  - stage: Deploy
    install:
    - openssl aes-256-cbc -K $encrypted_19679a0a12a5_key -iv $encrypted_19679a0a12a5_iv
      -in mussum_rsa.enc -out /tmp/mussum_rsa -d
    - chmod 400 /tmp/mussum_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add /tmp/mussum_rsa
    script: scp docker-compose.yml fsantiago@fsantiago.info:/home/fsantiago/mussum/ && ssh fsantiago@fsantiago.info "cd mussum && docker-compose pull && APIKEY=${TELEGRAM_TOKEN} docker-compose up --force-recreate -d"
# before_install:
# - openssl aes-256-cbc -K $encrypted_19679a0a12a5_key -iv $encrypted_19679a0a12a5_iv
#   -in mussum_rsa.enc -out /tmp/mussum_rsa -d
# - chmod 400 /tmp/mussum_rsa
# - eval "$(ssh-agent -s)"
# - ssh-add /tmp/mussum_rsa
