language: go
go:
- 1.x
services:
- docker
addons:
  ssh_known_hosts: fsantiago.info
jobs:
  include:
  - stage: Build & Test & Publish
    script: make build && scripts/publish.sh
  - stage: Deploy
    script: scripts/ssh-setup.sh && ssh -t fsantiago@fsantiago.info 'docker run -d -e APIKEY=${TELEGRAM_TOKEN} fsantiag/mussum:1.0.0'
env:
  global:
  - secure: E2brz1WW96x7/HKS6TqFxfav5/vpOsnd/z9GG5lVeYgNJKGZoac9yaoAuCQkeXr7h6QwpFHr9z/bXdbUvlnAFYlKj170er7NLK9z1by2MKrT1Eck2OMf9yosoevdJLjZJIt4jv12VsN6Jv0pSSG5HFs4EvLITujGaa+DjCV8Y7t2TYgJJ/kHyu8jqwAo2i146waDKGd7kvDqAU2ULGSdz14oQzxt5I9r/K3ealHKPna/dmQMuEomAz+rzsfBcqS0mtxBLyjLGYG0OgrlFU6/T54ZGX7RkVCTig8S4f8Xf63+u5H0aXlDiBM5ui6KYGdzOjWSNfbwQKhs7Y7PV+Gu4vkcyUokd3D0v2epf4+cNuKtu9rmLu0HKv4yu1Z/v6/xfrQEZD6qiXiiitKkkRng6UGNCm3q8ngHwzhZZ5nrcjXarXSqiT9yqSnmJk4Qg+TTCSQvuYquknJP4Gjw43ZnTQBzRIN+/O4vhYGJUQn21OW678G8+ui4NkUFk7twgrsFdsP6smXCYv8QFgPyBSgufNiOMfGqVMIhSxYCuMCaiO7iJX4YYV9CK03tS7mWQM3ZyIDCfgDPwQXClhNii48OWTqL2Qe5dKfxZqjvU9UBR2J+134jfhvHRHJhX402KNMbuz5d6r4XtTiAnnUcnzM4EdyEkK+Dv5nm5AEIb6nagwE=
  - secure: ecWiQ14mWh0I+H8cU9eYAMWov5GRU6UWSlld/yEAWIpjl8CYVpxRasCQ6pG+dLN+PcjothXJaaGqjxDTXRNYBtYTCxkkSKGwrDafZV5JW1ejtmaTU8njT6uL5pjPadlDh5WFKNmxTvg6Uz3fjqzNUWHst7upjrBkR0Papnc4MPADwONKFEYdexXNfrD8RZ3pQnc5XyRjXyBvhb0TL2wHk15wDiKqJUGbTw8tXwQYBN+yhpPqmJqh0usoYv1S8n1Bwc2BwTvLLorZ8G0vBC8fi5jf8hTNhcLT8FWhZHRnpxMkAop7bm0mJswL4WS8rfnUBOLtJhwxF1tAj0ESdtN2Ocz4cx1q2VNRshUztZ3YBeARrfqazh5/XEivxZwgJ6IscMKkXwbLfjamqns6DBVBt44bd5I9xbmI3+I/QIIF9NGXIfDUaTA13v/u0tFxozRZ3k89H7ecBAARTxsIDji6z1F1T697bq3UGnQPQCF46YVAVDKTidPkmLMAycvkMrkgqTyA8LhdhQm8PFWNbtdkbZDorok8c3vtCa2V8BetNbPtCtkN6bldUS3+Q+vlr/8cdQTNv5zmHKtTPQ41BDhdWA2b0l9oSlEBqmeSJ9/eKGNA5LnwmS20iMRm6ufY40oWMiJ+lc0wk52UFGIGBLtCHOZZy200GvTecthx/z+bP9o=
